apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nq4vb2x47-python
  janus-idp.io/tekton: nq4vb2x47-python
  backstage.io/kubernetes-id: nq4vb2x47-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nq4vb2x47-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
